#!/bin/sh
if test -f /etc/oss.conf
then
  . /etc/oss.conf
else
  OSSLIBDIR=/usr/lib/oss
fi

if test -f /proc/opensound/devfiles
then
	echo OSS is already loaded.
	exit 0
fi

if test -f $OSSLIBDIR/starting
then
	echo Previous start of OSS crashed the system
	echo Please resolve the situation and remove file
	echo \"$OSSLIBDIR/starting\". Then start OSS by
	echo running soundon again.
	exit 1
fi

NOTIFY=0

LOG=$OSSLIBDIR/logs/soundon.log
echo "Open Sound System starting" `date` > $LOG
echo "OSS version: " `cat $OSSLIBDIR/version.dat` >> $LOG 2>&1
KERNEL_VERSION=`uname -r`
echo "Kernel version: " $KERNEL_VERSION >> $LOG

if ! test -f $OSSLIBDIR/etc/installed_drivers
then
	echo No $OSSLIBDIR/etc/installed_drivers - running ossdetect >> $LOG
	/usr/sbin/ossdetect -v >> $LOG
fi

if ! test -f $OSSLIBDIR/etc/installed_drivers
then
	echo Still no $OSSLIBDIR/etc/installed_drivers - cannot continue >> $LOG
	echo No $OSSLIBDIR/etc/installed_drivers - cannot continue
	exit 10
fi

if ! test -f /lib/modules/`uname -r`/kernel/oss/osscore.o
then
	echo
	echo No /lib/modules/`uname -r`/kernel/oss/osscore.o module >> $LOG
	echo No /lib/modules/`uname -r`/kernel/oss/osscore.o module in the system
	exit 30
fi

if test -f $OSSLIBDIR/etc/license.asc
then
   /usr/sbin/ossdetect -l >> $LOG
fi

if ! sh $OSSLIBDIR/scripts/remove_drv.sh>> $LOG
then
	echo Failed to disable conflicting sound drivers >> $LOG
	echo Failed to disable conflicting sound drivers 
	echo Reboot and try running soundon again
	echo
	echo Also check that you have not compiled sound support statically
	echo into the kernel.
	exit 50
fi

touch $OSSLIBDIR/starting
sync

echo >> $LOG
echo '*** Loading OSS kernel modules ***' >> $LOG
echo >> $LOG

OPTIONS=
if test -f $OSSLIBDIR/conf/osscore.conf
then
  OPTIONS="`grep -v -h '^#' $OSSLIBDIR/conf/osscore.conf|sed 's/ //g'`"
fi

if ! /sbin/modprobe osscore $OPTIONS
then
	echo Loading the osscore module failed
	echo Loading the osscore module failed >> $LOG
	dmesg >> $LOG
	exit 60
fi

echo "osscore module loaded OK" >> $LOG

for n in `cat $OSSLIBDIR/etc/installed_drivers | sed 's/#.*//'`
do
	OPTIONS=

	if test -f $OSSLIBDIR/conf/$n.conf
	then
	  OPTIONS="`grep -v -h '^#' $OSSLIBDIR/conf/$n.conf|sed 's/ //g'`"
	fi

	if ! /sbin/modprobe $n $OPTIONS
	then
		echo Loading module $n failed '-' ignored >> $LOG
		echo Loading module $n failed '-' ignored
	else
		echo $n module loaded OK >> $LOG
	fi
done
echo >> $LOG
echo '*** Finished loading OSS kernel modules ***' >> $LOG
echo >> $LOG

if ! test -f /proc/opensound/devfiles
then
	echo OSS Core module refused to start >> $LOG
	echo OSS Core module refused to start
	dmesg >> $LOG
	exit 70
fi

/usr/sbin/ossdetect -d >> $LOG 2>&1

# Restore the legacy device links. This is necessary because in some
# Linux distributions they get lost when the system is booted.
if test -f $OSSLIBDIR/etc/legacy_devices
then
	sh $OSSLIBDIR/etc/legacy_devices >> $LOG 2>&1
fi

/usr/sbin/ossdevlinks -v >> $LOG 2>&1

echo "+++ ossinfo -v3 +++" >> $LOG
ossinfo -v3 >> $LOG 2>&1
echo "+++ /dev/sndstat +++" >> $LOG
cat /dev/sndstat >> $LOG 2>&1
echo "+++ dmesg +++" >> $LOG
dmesg >> $LOG
echo "+++ lspci +++" >> $LOG
lspci -v >> $LOG 2>&1
echo "+++ /proc/interrupts +++" >> $LOG
cat /proc/interrupts >> $LOG 2>&1
echo "+++ /proc/cpuinfo +++" >> $LOG
cat /proc/cpuinfo >> $LOG 2>&1
echo "+++ /proc/opensound/devfiles +++" >> $LOG
cat /proc/opensound/devfiles >> $LOG 2>&1
ls -l /dev/dsp* /dev/mixer* /dev/midi* /dev/oss/*/* >> $LOG 2>&1

/usr/sbin/savemixer -L >> $LOG 2>&1

# Setup ALSA emulation

if test -f $OSSLIBDIR/.cuckoo_installed
then
# Use kernel based ALSA compatibility

  if ! test -f /lib/modules/`uname -r`/kernel/sound/core/snd.o
  then
	sh $OSSLIBDIR/scripts/setup-alsa.sh >> $LOG 2>&1
  	depmod -a
  fi

  echo "*** Setting up ALSA compatibility ****" >> $LOG
  modprobe cuckoo >> $LOG 2>&1
  head -10 /proc/asound/version >> $LOG 2>&1
  lsmod|grep snd >> $LOG
  echo "**************************************" >> $LOG
else
# Use library based ALSA compatibility

  if test -f $OSSLIBDIR/lib/libsalsa.so.2.0.0
  then
     if test "`uname -m` " = "x86_64 "
     then
       ln -sf $OSSLIBDIR/lib/libsalsa.so.2.0.0 /usr/lib64/libasound.so.2
       ln -sf $OSSLIBDIR/lib/libOSSlib.so /usr/lib64
     else
       if test -s /lib/libasound.so.2
       then
         ln -sf $OSSLIBDIR/lib/libsalsa.so.2.0.0 /lib/libasound.so.2
         ln -sf $OSSLIBDIR/lib/libOSSlib.so /lib
       fi
  
       if test -s /usr/lib/libasound.so.2
       then
         ln -sf $OSSLIBDIR/lib/libsalsa.so.2.0.0 /usr/lib/libasound.so.2
         ln -sf $OSSLIBDIR/lib/libOSSlib.so /usr/lib
       fi
     fi
  fi
fi

# Setup Flash 9 audio support plugin for OSS

if test -f $OSSLIBDIR/lib/libflashsupport.so
then
  rm -f /usr/lib/libflashsupport.so
  ln -sf $OSSLIBDIR/lib/libflashsupport.so /usr/lib/libflashsupport.so
fi

if test -x $OSSLIBDIR/soundon.user
then
  echo Running $OSSLIBDIR/soundon.user >> $LOG
  $OSSLIBDIR/soundon.user >> $LOG 2>&1
fi

if test "$NOTIFY " = "1 "
then
  echo
  echo OSS started OK
fi

rm -f $OSSLIBDIR/starting

exit 0
