#ifndef OSS_ERRNO_H
#define OSS_ERRNO_H

#ifndef OSS_NEGATIVE_ERRNO
#define OSS_NEGATIVE_ERRNO(x) -x
#endif

#define OSS_E2BIG		OSS_NEGATIVE_ERRNO( E2BIG )
#define OSS_EACCES		OSS_NEGATIVE_ERRNO( EACCES )
#define OSS_EAGAIN		OSS_NEGATIVE_ERRNO( EAGAIN )
#define OSS_EBADE		OSS_NEGATIVE_ERRNO( EBADE )
#define OSS_EBUSY		OSS_NEGATIVE_ERRNO( EBUSY )
#define OSS_ECONNRESET		OSS_NEGATIVE_ERRNO( ECONNRESET )
#define OSS_EDOM		OSS_NEGATIVE_ERRNO( EDOM )
#define OSS_EFAULT		OSS_NEGATIVE_ERRNO( EFAULT )
#define OSS_EIDRM		OSS_NEGATIVE_ERRNO( EIDRM )
#define OSS_EINTR		OSS_NEGATIVE_ERRNO( EINTR )
#define OSS_EINVAL		OSS_NEGATIVE_ERRNO( EINVAL )
#define OSS_EIO			OSS_NEGATIVE_ERRNO( EIO )
#define OSS_ELOOP		OSS_NEGATIVE_ERRNO( ELOOP )
#define OSS_ENODEV		OSS_NEGATIVE_ERRNO( ENODEV )
#define OSS_ENOENT		OSS_NEGATIVE_ERRNO( ENOENT )
#define OSS_ENOMEM		OSS_NEGATIVE_ERRNO( ENOMEM )
#define OSS_ENOSPC		OSS_NEGATIVE_ERRNO( ENOSPC )
#define OSS_ENOTSUP		OSS_NEGATIVE_ERRNO( ENOTSUP )
#define OSS_ENXIO		OSS_NEGATIVE_ERRNO( ENXIO )
#define OSS_EPERM		OSS_NEGATIVE_ERRNO( EPERM )
#define OSS_EPIPE		OSS_NEGATIVE_ERRNO( EPIPE )
#define OSS_ERANGE		OSS_NEGATIVE_ERRNO( ERANGE )
#define OSS_EWOULDBLOCK		OSS_NEGATIVE_ERRNO( EWOULDBLOCK )

#endif
